version: "3.8"

services:
  node:
    image: shjhwoo/types
    build: .
    working_dir: /usr/src/app
    restart: always
    volumes:
      - "./:/usr/src/app"
    ports:
      - "1234:5000"
    container_name: helloworld
